In [1]:
dev = "AIzaSyA72LL5ASeFWI2ZgjO8bGIZ7RlDbs4fy30"

**Get Comments Function**

In [2]:
import googleapiclient.discovery
import pandas as pd

api_service_name = "youtube"
api_version = "v3"
DEVELOPER_KEY = dev

youtube = googleapiclient.discovery.build(
    api_service_name, api_version, developerKey=DEVELOPER_KEY)


def getcomments(video):
  request = youtube.commentThreads().list(
      part="snippet",
      videoId=video,
      maxResults=100
  )

  comments = []

  # Execute the request.
  response = request.execute()

  # Get the comments from the response.
  for item in response['items']:
      comment = item['snippet']['topLevelComment']['snippet']
      public = item['snippet']['isPublic']
      comments.append([
          comment['authorDisplayName'],
          comment['publishedAt'],
          comment['likeCount'],
          comment['textOriginal'],
          comment['videoId'],
          public
      ])

  while (1 == 1):
    try:
     nextPageToken = response['nextPageToken']
    except KeyError:
     break
    nextPageToken = response['nextPageToken']
    # Create a new request object with the next page token.
    nextRequest = youtube.commentThreads().list(part="snippet", videoId=video, maxResults=100, pageToken=nextPageToken)
    # Execute the next request.
    response = nextRequest.execute()
    # Get the comments from the next response.
    for item in response['items']:
      comment = item['snippet']['topLevelComment']['snippet']
      public = item['snippet']['isPublic']
      comments.append([
          comment['authorDisplayName'],
          comment['publishedAt'],
          comment['likeCount'],
          comment['textOriginal'],
          comment['videoId'],
          public
      ])

  df2 = pd.DataFrame(comments, columns=['author', 'updated_at', 'like_count', 'text','video_id','public'])
  return df2

In [11]:
df = getcomments('SYe-x9ZQF7o')
df

,author,updated_at,like_count,text,video_id,public
0,@nohu-z1,2022-06-24T16:55:44Z,8182,আপনারা কি জানেন... আইয়ুব বাচ্চুর সেই তুমি গান...,SYe-x9ZQF7o,True
1,@Onamikaislam-g1g,2026-06-11T17:49:14Z,0,Choto bela theke ai gan ta onek sondor lagto❤❤,SYe-x9ZQF7o,True
2,@MdRamim-zo2oh,2026-06-11T12:44:43Z,0,কেনাে যানি আমি এই গান টা শুনলে আমার বুকের ভিতর...,SYe-x9ZQF7o,True
3,@AlaminShikdar-o9x,2026-06-09T13:44:04Z,0,2026 কে কে আছো,SYe-x9ZQF7o,True
4,@jhemon3243,2026-06-09T13:28:38Z,0,❤️,SYe-x9ZQF7o,True
...,...,...,...,...,...,...
8032,@mdsk124,2022-04-23T16:15:54Z,1,I love this song,SYe-x9ZQF7o,True
8033,@jamansristy8218,2022-04-23T14:44:37Z,0,Copyright khaben toh😐,SYe-x9ZQF7o,True
8034,@A_A_Muhit,2022-04-23T11:20:20Z,0,Apu apner Video onk valo hoy. Apni caila amede...,SYe-x9ZQF7o,True
8035,@ShamimAkound,2022-04-23T07:46:51Z,3,😍😍😍,SYe-x9ZQF7o,True
8036,@asifahmed7863,2022-04-23T07:25:54Z,0,😢😢😢,SYe-x9ZQF7o,True

**For Loop for List of Video IDs**

In [12]:
df = pd.DataFrame()
for i in ['rz-QcZLszy4','SYe-x9ZQF7o','04FxMouVtic','-R7_wSmDRrs','H_wGmAjI_wM', 'v2K9qDePmW4', 'F-YoFMhZEx8', 'wjjyxAh5Tek', 'jGB-16XbpmA']:
  df2 = getcomments(i)
  df = pd.concat([df, df2])

In [13]:
df

,author,updated_at,like_count,text,video_id,public
0,@samiulalam9895,2026-06-11T18:18:39Z,0,জতো দিন বেচে আছি \nসারাজীবন ভালো বেসে জাবো বাচ...,rz-QcZLszy4,True
1,@robinAhmed-u5l,2026-06-05T18:35:40Z,0,রুচিশীল মিউজিক প্রেমীদের প্রথম তালিকায় থাকে এস...,rz-QcZLszy4,True
2,@abusalehshoaib730,2026-05-04T17:14:31Z,0,RIP The Magical Musician Ayub Bacchu.... ❤❤❤❤,rz-QcZLszy4,True
3,@AamarjanSathi,2026-04-28T15:18:38Z,0,🇧🇩🇧🇩🇧🇩🇧🇩🥰🥰🥰🥰😅😅😅😅😅🤗🤗🤗❤️❤️❤️,rz-QcZLszy4,True
4,@arefurbd,2026-04-23T23:21:50Z,0,"I am portraying this song on my daughter, in V...",rz-QcZLszy4,True
...,...,...,...,...,...,...
700,@durjoyrajbongshi7022,2022-04-06T14:14:16Z,1,Loop e atke gechi❤️,jGB-16XbpmA,True
701,@mahanajhossainudoy2452,2022-04-06T14:10:27Z,0,Khub beshi shundor <3,jGB-16XbpmA,True
702,@asifurrahmanimon4746,2022-04-06T11:15:22Z,0,ভালোবাসি কাকতাল❤️🌼,jGB-16XbpmA,True
703,@mahinalom2968,2022-04-06T09:46:18Z,0,😌💖,jGB-16XbpmA,True
704,@whereisraimur,2022-04-06T08:15:27Z,0,অসাধারণ,jGB-16XbpmA,True

In [14]:
df['video_id'].value_counts()

video_id
SYe-x9ZQF7o    8037
H_wGmAjI_wM    5733
04FxMouVtic    1193
F-YoFMhZEx8    1167
jGB-16XbpmA     705
v2K9qDePmW4     365
rz-QcZLszy4     198
wjjyxAh5Tek     174
-R7_wSmDRrs     113
Name: count, dtype: int64

In [15]:
df.to_excel("Multiple Video Comments.xlsx", index=False)

In [16]:
from google.colab import files

files.download("Multiple Video Comments.xlsx")