**For single video's comment extraction, we can use the following Python script.**

In [5]:
dev = "AIzaSyA72LL5ASeFWI2ZgjO8bGIZ7RlDbs4fy30"

In [99]:
import googleapiclient.discovery
import pandas as pd

api_service_name = "youtube"
api_version = "v3"
DEVELOPER_KEY = dev

youtube = googleapiclient.discovery.build(
    api_service_name, api_version, developerKey=DEVELOPER_KEY)

request = youtube.commentThreads().list(
    part="snippet",
    videoId="WPxfbxbE9ak",
    maxResults=100
)

comments = []

# Execute the request.
response = request.execute()

# Get the comments from the response.
for item in response['items']:
    comment = item['snippet']['topLevelComment']['snippet']
    public = item['snippet']['isPublic']
    comments.append([
        comment['authorDisplayName'],
        comment['publishedAt'],
        comment['likeCount'],
        comment['textOriginal'],
        public
    ])

while (1 == 1):
  try:
   nextPageToken = response['nextPageToken']
  except KeyError:
   break
  nextPageToken = response['nextPageToken']
  # Create a new request object with the next page token.
  nextRequest = youtube.commentThreads().list(part="snippet", videoId="-GJgqIJsTME", maxResults=100, pageToken=nextPageToken)
  # Execute the next request.
  response = nextRequest.execute()
  # Get the comments from the next response.
  for item in response['items']:
    comment = item['snippet']['topLevelComment']['snippet']
    public = item['snippet']['isPublic']
    comments.append([
        comment['authorDisplayName'],
        comment['publishedAt'],
        comment['likeCount'],
        comment['textOriginal'],
        public
    ])

df = pd.DataFrame(comments, columns=['author', 'updated_at', 'like_count', 'text','public'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 793 entries, 0 to 792
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   author      793 non-null    object
 1   updated_at  793 non-null    object
 2   like_count  793 non-null    int64
 3   text        793 non-null    object
 4   public      793 non-null    bool
dtypes: bool(1), int64(1), object(3)
memory usage: 25.7+ KB

In [100]:
if response['items']:
    response['items'][0]
else:
    print("The 'items' list in the response is empty. No comments were retrieved for the video ID used in the last API call.")

In [104]:
df.head(20)

,author,updated_at,like_count,text,public
0,@NooneTasin,2026-05-15T06:21:48Z,0,Ami vabtam Ami e Jibito las But Ai khane dakci...,True
1,@porbomendas1740,2026-05-15T04:57:08Z,0,Like dew kew plz😅😢,True
2,@AlifBinAshraf,2026-05-12T02:30:47Z,0,Aj porjonto kono like pelam na 😢,True
3,@সুপ্তসজিব,2026-05-11T16:54:45Z,0,যে দু:খ তুমি বুজো নাই \nসেই দু:খের কথা আমি কাউ...,True
4,@HappyKitun,2026-05-11T15:37:33Z,0,আমি ভালো বাসার কোনো কমতি ছিলো না কিন্তু ও আ...,True
5,@sheikhraseldhaka-1383,2026-05-10T15:49:35Z,0,তোমাকে পেয়ে গেলে গানটি শুনন হতো না।ধন্যবাদ স্মৃতি,True
6,@MafujSheikh-q1c,2026-05-10T12:51:03Z,0,❤😅,True
7,@SamiUllah-q4p7w,2026-05-09T22:04:48Z,0,Ajke Physics exam. R ami rat 4 tai asci ei gan...,True
8,@Ayeshaakterarifa-u2t1j,2026-05-09T15:24:42Z,0,Ei ganta je shudu seleder Jonno na amraw kisu ...,True
9,@SocR-t2x,2026-05-08T21:09:26Z,0,সে ছিলো এবং আছে আমার বেস্ট ফ্রেন্ড \nকিন্তু আম...,True
10,@ShantaAktar-q7n3m,2026-05-07T03:51:30Z,0,Fvrt song🫠😌,True
11,@TanvirIslam-j6n,2026-05-05T17:50:04Z,0,আসোরে বসে গান টা শুনলাম 🚬🚬,True
12,@sabbirrahman855,2026-05-05T06:01:57Z,1,2০ বছর বয়সে তোমাকে পেয়ে হারানোর তীব্র কষ্ট আমা...,True
13,@rockisback6449,2026-05-01T08:45:54Z,0,😅😅 mon er moto ekta gan,True
14,@MdHelal-e7i2b,2026-04-30T21:53:53Z,0,The person i loved before my eyes became someo...,True
15,@RXRIYAD-v4h,2026-04-30T21:42:41Z,0,Amr prio manus ta ar amr nai 😅❤️‍🩹1:28,True
16,@AzizKhan-t1o9d,2026-04-28T19:24:38Z,0,❤❤❤,True
17,@Mestersalman22,2026-04-28T17:17:49Z,0,ও আমায় ভালোবাসে নি 😅💔🩹,True
18,@simaislam8282,2026-04-28T16:38:48Z,1,ঈদের পর তার বিয়ে 😅 সে আমায় বলেছিলো দুই ফ্যামিল...,True
19,@Ijsthr,2026-04-28T14:50:24Z,2,এই গানটা প্রথম শুনেছি তার মুখেই।😅বুঝিনাই আমার...,True

In [102]:
df.sort_values(by='like_count', ascending=False)[0:30]

,author,updated_at,like_count,text,public
777,@Slickvic97,2023-10-23T15:05:54Z,1125,Action needs an 8 part series in every country...,True
680,@Nolanbrown480,2023-10-23T16:59:12Z,783,Clovis’ energy is absolutely unmatched. The pe...,True
645,@ActionBronsonMusic,2023-10-23T17:53:02Z,614,PARIS. WITH LOVE.,True
782,@uknownutin3528,2023-10-23T15:01:03Z,556,One of the best food series on YouTube. LONG L...,True
791,@2xW-Man,2023-10-23T12:30:09Z,283,One of the best and most authentic eating shows,True
731,@urbanprojectz,2023-10-23T15:59:02Z,184,This is a game changer for food/cooking/review...,True
661,@yorkshireguy6671,2023-10-23T17:15:43Z,79,Action and Clovis in Paris always looks like t...,True
755,@elmejortrabajodelmundo,2023-10-23T15:26:47Z,77,"""From Paris with Love"" makes me happy for real...",True
790,@cheng8841,2023-10-23T12:57:26Z,70,"""eight part series"" LETS GOOOOOO",True
741,@Raisinsetmelodies,2023-10-23T15:42:38Z,52,Thanks for putting forward the bottles that th...,True
679,@JohnMHatch,2023-10-23T16:59:39Z,50,Everybody needs a friend like Clovis,True
759,@InspectahReese,2023-10-23T15:25:27Z,48,If y’all love Clovis he raps in French! You ha...,True
696,@gijoey5912,2023-10-23T16:43:41Z,30,I’m not a big wine guy but this show always ma...,True
397,@hris1473,2023-10-24T18:35:58Z,25,"never let these series end,they bring me so mu...",True
619,@southport65,2023-10-23T19:03:16Z,19,"man, i could not stop grinning ear-to-ear watc...",True
428,@Seiji504,2023-10-24T11:09:56Z,18,I prolly watched the Paris series with Clovis ...,True
715,@bballa0608,2023-10-23T16:13:56Z,15,Vice messed up with not continuing with this g...,True
640,@toooj,2023-10-23T18:06:13Z,13,It's crazy Action can make me feel the same lo...,True
789,@ec6678,2023-10-23T13:33:21Z,12,Watch out for those bed bugs,True
691,@subressor1,2023-10-23T16:49:46Z,7,"Loved the last Paris series, an iconic series ...",True
395,@BamMetaX,2023-10-24T19:19:34Z,7,Never fails. Wish these were half hour episode...,True
59,@MdNahian-z2r,2026-04-03T19:44:53Z,7,তোমাকে পেয়ে গেলে হয়তো এতো সুন্দর গানটা শোনা হত...,True
318,@CruxalYT,2023-10-25T22:46:02Z,6,Mannnn to think of how much LIFE I've lived si...,True
531,@calzzz5610,2023-10-23T23:44:30Z,6,I was just telling my friends the other day ho...,True
742,@4sebek,2023-10-23T15:42:30Z,6,Action's on fire recently. Sensational food an...,True
78,@RubelRana-k3c,2026-03-17T11:55:05Z,5,Abar comment kore gelam like dile sunte asbo 😅,True
749,@tawandajerry1,2023-10-23T15:32:30Z,5,Clovis needs a spin off show,True
567,@sebastianlohmann7544,2023-10-23T21:42:37Z,5,Imagine hanging out with these guys. Couldn’t ...,True
653,@tally_mon7587,2023-10-23T17:37:05Z,5,The original from paris with love series are s...,True
569,@YoungManDub,2023-10-23T21:36:27Z,4,Where's Alc? Body? Mayhem,True

In [105]:
df = pd.DataFrame(comments)

# Export to Excel
df.to_excel("Dukkho Bilash V-1.xlsx", index=False)

In [106]:
from google.colab import files

files.download("Dukkho Bilash V-1.xlsx.xlsx")